### ISSUE TITLE
Asus Chromebox 3: can't boot from USB-C Power Delivery after flashing UEFI firmware

### ISSUE THREAD

**Issue by bam80** [MrChromebox/firmware#595]
First of all it still boots from power adapter.
Then, if I swap to PD with WP screw in place, LED blinking red and it doesn't boot.
If I remove the screw, it bootloops.

With original firmware, I can boot from PD with screw in place only. If I remove the screw, get bootloop (need to detach from power before removing the screw, otherwise it can still boot).

So it seems no way of using native Linux with PD currently, which is a whole point I bought the device.

Any help? @MrChromebox could you try to reproduce, please?

**Comment by bam80** [comment]
> With original firmware, I can boot from PD with screw in place only. If I remove the screw, get bootloop (need to detach from power before removing the screw, otherwise it can still boot).

This particular issue is reported here:
https://issuetracker.google.com/issues/222675683

**Comment by MrChromebox** [comment]
closing as this isn't a script issue

**Comment by bam80** [comment]
Could we move the issue between projects?
This should be placed in https://github.com/MrChromebox/firmware/issues instead.

First needs to be reopened:
https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by bam80** [comment]
> Could we move the issue between projects?

@MrChromebox

**Comment by bam80** [comment]
> closing as this isn't a script issue

Thank you for the transferring, I suppose we can reopen it now?

I'll have Suzy-Q cable soon so can provide more data hopefully.

**Comment by MrChromebox** [comment]
all 3 CN65s I have here boot via USB-C PD and provide video via USB-C PD

**Comment by bam80** [comment]
@MrChromebox as we discussed, the problem might expose only with certain PD sources (as specific display models, etc.).
Still it was specific to this Coreboot fork.

Having that, I think it would be reasonable to keep this issue open, until more data come.

**Comment by MrChromebox** [comment]
is it a coreboot issue? I suspect not. would need to compare ECRW builds between stock and my fw to see if there's something in the ECRW update causing a problem

**Comment by bam80** [comment]
Thank you for reopening.

With the original firmware, I can boot at least somehow:
> With original firmware, I can boot from PD with screw in place only. If I remove the screw, get bootloop (need to detach from power before removing the screw, otherwise it can still boot).

I didn't update for a long time though, but will return to all this soon.

BTW, if you remind me how could I get fresh original Google's firmware for the test, that would be helpful.
Thanks.

**Comment by bam80** [comment]
> would need to compare ECRW builds between stock and my fw to see if there's something in the ECRW update causing a problem

Sorry I forgot the details, do you need my assistant for that?

**Comment by druby-luke** [comment]
Hi, is there any update on this? im having the same issue with my CXI3. 

fun thing is, non of my usb c chargers seem to work AFTER removing the screw and installing coreboot. But my OEM Lenovo adapter from my thinkpad with 65 watt seem to work: 

lenovo SA10R16921 , to be exact.

**Comment by bam80** [comment]
@druby-luke I reported the issue upstream, and they requested the test with USB-C PD power adapter (vs display with PD output I have). I don't have the adapter currently, so please chime in and report here carefully, with your hardware models, etc.:
https://issuetracker.google.com/issues/222675683#comment3

Also, it would be helpful if you could make your own debug cable for tests (or buy it). I could help with that.

Thanks.

**Comment by bam80** [comment]
> I reported the issue upstream

@MrChromebox did you follow the replies? They might provide some insight:
https://issuetracker.google.com/issues/222675683#comment11

**Comment by MrChromebox** [comment]
there's nothing new there for well over a year, and the EC should be/stay in RW once it's updated and has transitioned from RO to RW unless there's a full power loss.

On my TEEMO boards here, the box will boot without problem from a USB-PD charger via USB-C. It will not boot when connected via USB-C to a monitor which does USB-PD (~85W).

There's no good way for me to debug this since the debug interface is the SuzyQ cable which connects to the USB-C port, so I can't use that and reproduce the issue simultaneously

**Comment by bam80** [comment]
> It will not boot when connected via USB-C to a monitor which does USB-PD

IIRC it worked for you earlier, has something changed?
BTW, what is your USB-PD charger?

**Comment by MrChromebox** [comment]
I don't recall it ever working with only the USB-C monitor connection.

the PD brick is a Lenovo 65W one, probably from a Chromebook

**Comment by bam80** [comment]
> all 3 CN65s I have here boot via USB-C PD and provide video via USB-C PD

@MrChromebox so these were not booted  from display's PD?

**Comment by MrChromebox** [comment]
> > all 3 CN65s I have here boot via USB-C PD and provide video via USB-C PD
> 
> @MrChromebox so these were not booted from display's PD?

I assume I meant that comment as the functions worked independently

**Comment by bam80** [comment]
> non of my usb c chargers seem to work AFTER removing the screw and installing coreboot

@druby-luke could you name these chargers?

**Comment by bam80** [comment]
> I don't recall it ever working with only the USB-C monitor connection.

@MrChromebox could you test with original FW?
It worked for me:
> With original firmware, I can boot from display's PD with screw in place only. If I remove the screw, get bootloop (need to detach from power before removing the screw, otherwise it can still boot).

**Comment by druby-luke** [comment]
> > non of my usb c chargers seem to work AFTER removing the screw and installing coreboot
> 
> @druby-luke could you name these chargers?

sure!

UGreen 100 watt GAN charger 
Ikea 45 watt dual charger 
a random nameless 65 watt charger (that confirmed worked before with OEM firmware)
steamdeck OEM 45 watt adapter
Dell 45 watt XPS13 adapter 
LG screen with a usb C cable that runs 90 watts

**Comment by bam80** [comment]
@druby-luke thanks, are you sure 45 W should boot at least?

**Comment by druby-luke** [comment]
no I'm not, because the Ugreen did not work I just tried every usb C charger I could find at home haha.

**Comment by bam80** [comment]
> a random nameless 65 watt charger (that confirmed worked before with OEM firmware)

@MrChromebox don't you think even without proper debugging equipment, we should be able to bisect the problem?

**Comment by MrChromebox** [comment]
> @MrChromebox don't you think even without proper debugging equipment, we should be able to bisect the problem?

the problem seems to exist with the stock firmware and the WP screw removed as well, no? 

Has anyone tried with the screw reinstalled after flashing my firmware?

**Comment by bam80** [comment]
> the problem seems to exist with the stock firmware and the WP screw removed as well, no?

In my case that was true, see the OP:

> With original firmware, I can boot from PD with screw in place only. If I remove the screw, get bootloop (need to detach from power before removing the screw, otherwise it can still boot).

  
> Has anyone tried with the screw reinstalled after flashing my firmware?

I tried it both ways (and cold boot too), dead end:
> First of all it still boots from power adapter.
Then, if I swap to PD with WP screw in place, LED blinking red and it doesn't boot.
If I remove the screw, it bootloops.

**Comment by MrChromebox** [comment]
I'd have to go digging deep into the PD code in the EC to try and sort this out, and it's not something I'm familiar with at all

**Comment by bam80** [comment]
Still, could bisecting give us some low hanging fruits, for start? Looks probable to me.

**Comment by MrChromebox** [comment]
bisecting what exactly?

**Comment by bam80** [comment]
I would start with building some upstream fw version and test it.
If it works - start to apply your changes, test again and thus bisect.

**Comment by MrChromebox** [comment]
there are no changes in coreboot that would affect the EC/PD at all.

The ECRW update is just the tip of the firmware branch.  One could test using Google's latest ECRW update instead of mine and see if that behaves the same way as the stock firmware, that would allow us to have an endpoint to bisect from

**Comment by bam80** [comment]
> One could test using Google's latest ECRW update instead of mine

How one would do that, exactly?
Does something prebuilt exist, or we need to build ourselves?
Could you describe the steps in details, or maybe you could test it yourself?

**Comment by MrChromebox** [comment]
actually, looks like Google's latest ECRW update for Fizz is the same as mine save for the version string

**Comment by MrChromebox** [comment]
here's a test build with Google's ECRW vs mine, just in case it's a compiler issue. If this behaves the same as the public release, then I suspect the issue might be something with depthcharge/vboot

[coreboot_edk2-fizz-mrchromebox_20240923.zip](https://github.com/user-attachments/files/17104856/coreboot_edk2-fizz-mrchromebox_20240923.zip)

**Comment by bam80** [comment]
Thank you, unfortunately, I can't test myself at the moment.
I would certainly assist but not now.
So if you could test it yourself that would be awesome.

**Comment by MrChromebox** [comment]
I did some testing, and keeping the EC in RO mode allows it to boot via PD from a monitor connection. It's the RO->RW transition that's causing the reset -- though according to the documentation, it shouldn't:

https://chromium.googlesource.com/chromiumos/platform/ec/+/HEAD/docs/usb-c.md#implementation-considerations

**Comment by bam80** [comment]
@MrChromebox Awesome, it's great to hear the progress!

Some preliminary questions:
> keeping the EC in RO mode allows it to boot via PD from a monitor connection
- How one could reproduce your success test to confirm it? There is still a chance we have mix of the problems here.
- Do you have idea about short-term workaround? Long-term solution?
- Could we adopt TCPMv2 on Fizz and try it there?
https://chromium.googlesource.com/chromiumos/platform/ec/+/HEAD/docs/usb-tcpmv2.md

> It's the RO->RW transition that's causing the reset

It's still not clear to me:
Stock FW still can boot with the WP screw in, why can't we behave the same?

**Comment by MrChromebox** [comment]
> * How one could reproduce your success test to confirm it? There is still a chance we have mix of the problems here.

flash a test build which doesn't switch the EC from RO to RW at boot

> * Do you have idea about short-term workaround? Long-term solution?

keep the EC in RO. fix the transition if possible

> * Could we adopt TCPMv2 on Fizz and try it there?
>   https://chromium.googlesource.com/chromiumos/platform/ec/+/HEAD/docs/usb-tcpmv2.md

probably not, Fizz doesn't use a dedicated TCPM chip and backporting the code to Fizz's EC would not be a small undertaking

> > It's the RO->RW transition that's causing the reset
> 
> It's still not clear to me: Stock FW still can boot with the WP screw in, why can't we behave the same?

who knows

**Comment by bam80** [comment]
> flash a test build which doesn't switch the EC from RO to RW at boot

If that succeeds, could we incorporate the change into your fork?

> keep the EC in RO

Is RO still a flash memory? Could we flash it by any mean - with a programmer or debug cable?

>  It's still not clear to me: Stock FW still can boot with the WP screw in, why can't we behave the same?

I mean - with the screw in, stock fw does PD contract solely in EC RW, right? So the RO->RW transition doesn't happen. Can we do the same, eliminating the transition?
IIUC, in your test above it happens in RO, but can we do it in RW instead?

**Comment by MrChromebox** [comment]
> > flash a test build which doesn't switch the EC from RO to RW at boot
> 
> If that succeeds, could we incorporate the change into your fork?

no, because RO firmware is (much) older, and I can't guarantee stability with a 8 year old RO build
 
> > keep the EC in RO
> 
> Is RO still a flash memory? Could we flash it by any mean - with a programmer or debug cable?

RO is just a flash region on the EC flash chip. It can be flashed like any other. But it's not as easy as RW -- ideally you flash the region that isn't active.

> > It's still not clear to me: Stock FW still can boot with the WP screw in, why can't we behave the same?
> 
> I mean - with the screw in, stock fw does PD contract solely in EC RW, right? So the RO->RW transition doesn't happen. Can we do the same, eliminating the transition? IIUC, in your test above it happens in RO, but can we do it in RW instead?

No. With the stock firmware, EC is always in RW except when the device is booted into recovery mode.

**Comment by bam80** [comment]
> RO is just a flash region on the EC flash chip. It can be flashed like any other. But it's not as easy as RW -- ideally you flash the region that isn't active.

Maybe that could be an optional workaround on our side - support flashing RO from the install script. Could we think about it?

> With the stock firmware, EC is always in RW

Anyway, what prevents us from doing the same?

**Comment by MrChromebox** [comment]
> > RO is just a flash region on the EC flash chip. It can be flashed like any other. But it's not as easy as RW -- ideally you flash the region that isn't active.
> 
> Maybe that could be an optional workaround on our side - support flashing RO from the install script. Could we think about it?

Absolutely not, it's not safe to do.

> > With the stock firmware, EC is always in RW
> 
> Anyway, what prevents us from doing the same?

we are doing the same thing effectively. Without power, the EC boots in RO, switches to RW (via coreboot), then stays in RW until power lost. I don't have any explanation as to why USB-PD + DP-alt mode works with the stock firmware but not upstream coreboot.

**Comment by bam80** [comment]
> it's not safe to do.

I guess so, that is why I said _optional_. If user is affected by this issue and has the debug cable, could he flash RO relatively safe?

**Comment by MrChromebox** [comment]
> > it's not safe to do.
> 
> I guess so, that is why I said _optional_. If user is affected by this issue and has the debug cable, could he flash RO relatively safe?

I don't have either the tools or a process to direct people on how to do that

**Comment by bam80** [comment]
> we are doing the same thing effectively. Without power, the EC boots in RO, switches to RW (via coreboot), then stays in RW until power lost.

- With the WP screw in, when the first time PD contract starts in both cases (our and stock ) - in RW?
- If so, if the switch happens via coreboot, does it mean AP starts initially without the contract?
- Can we use the same EC RW as stock?

**Comment by MrChromebox** [comment]
> > we are doing the same thing effectively. Without power, the EC boots in RO, switches to RW (via coreboot), then stays in RW until power lost.
> 
> * With the WP screw in, when the first time PD contract starts in both cases (our and stock ) - in RW?

RO

> * If so, if the switch happens via coreboot, does it mean AP starts initially without the contract?

switch happens in coreboot with upstream, in vboot with stock

> * Can we use the same EC RW as stock?

I already tested that last night, the behavior is the same as with my update.

**Comment by bam80** [comment]
>  > With the WP screw in, when the first time PD contract starts in both cases (our and stock ) - in RW?

> RO

The google docs and the answer in the bugtracker above state it's in RW in this case, isn't it?

https://chromium.googlesource.com/chromiumos/platform/ec/+/HEAD/docs/usb-c.md#implementation-considerations

> PD communication is disabled in locked RO images (normal state for customer devices). When the jump from RO to RW happens relatively quickly (e.g. there is not a long memory training step), then there aren't many problems when RW takes over and negotiates higher PD contracts.

https://issuetracker.google.com/issues/222675683#comment5
> PD is disabled in RO for security reason. When WP is disabled, we consider the device is not protected. So, we let the EC negotiate PD in RO. This is not always good because EC-RW doesn't completely take over the PD contract made by EC-RO. If it's not a handled case, EC-RW resets the port.

**Comment by MrChromebox** [comment]
it depends on whether power was completely removed from the EC, it can't start in RW from a cold boot

**Comment by bam80** [comment]
I thought where EC starts and where PD contract starts are two different things not necessary correlating to each other, and those descriptions are for cold boot as it's not stated the opposite.

**Comment by MrChromebox** [comment]
> I thought where EC starts and where PD contract starts are two different things not necessary correlating to each other, and those descriptions are for cold boot as it's not stated the opposite.

having the screw installed does not automatically enable WP -- it just prevents changes to software WP. One would have to examine the EC code to see how exactly it determines if WP is enabled / whether to enable PD for RO

**Comment by MrChromebox** [comment]
I have a colleague at Google looking into the bug report / might be able to provide some direction here.
https://issuetracker.google.com/issues/172220407#comment4
would seem to show that the issue can be resolved by not renegotiating. I can carry that change in my builds if I know what it is -- we'll see what I can find out.

**Comment by aaboagye** [comment]
One potential solution would be to do the following:

- Add a battery backed RAM (BBRAM) variable to store an index
- Save off the PDO index whenever a PD request message is sent; place this index in the BBRAM variable
- After the PD task starts and checks for an existing explicit contract, you could consult the BBRAM variable for the index and re-request that instead of vSafe5V.

**Comment by MrChromebox** [comment]
> One potential solution would be to do the following:
> 
> * Add a battery backed RAM (BBRAM) variable to store an index
> * Save off the PDO index whenever a PD request message is sent; place this index in the BBRAM variable
> * After the PD task starts and checks for an existing explicit contract, you could consult the BBRAM variable for the index and re-request that instead of vSafe5V.

great, let me know when you have it implemented

**Comment by druby-luke** [comment]
Small update from me, just received brand new Lenovo 65 watt chargers and they seem to work fine with the current release mrchromebox firmware without the write screw inserted.

Lenovo 4X20M26272 to be exact.

**Comment by MrChromebox** [comment]
I've been unsuccessful so far with modifying the PD code, need to have a better understanding of what's going on, so have a USB-PD sniffer on the way (thanks to a friend at Google) which hopefully will allow me to figure out the problem

**Comment by bam80** [comment]
> have a USB-PD sniffer on the way (thanks to a friend at Google) which hopefully will allow me to figure out the problem

Thanks for sharing us the details. Did you get the sniffer?

**Comment by MrChromebox** [comment]
> Thanks for sharing us the details. Did you get the sniffer?

not yet

**Comment by druby-luke** [comment]
Hi! is there perhaps any update on this?

**Comment by MrChromebox** [comment]
nope, still waiting to get the USB-PD sniffer to be able to debug further

**Comment by bam80** [comment]
> nope, still waiting to get the USB-PD sniffer to be able to debug further

If there is no estimate when it happens, maybe just try to blindly implement the solution suggested by @aaboagye above, meanwhile?
The test is simple: it's either boots or not.

**Comment by MrChromebox** [comment]
> > nope, still waiting to get the USB-PD sniffer to be able to debug further
> 
> If there is no estimate when it happens, maybe just try to blindly implement the solution suggested by @aaboagye above, meanwhile? The test is simple: it's either boots or not.

I already tried that without success

**Comment by MrChromebox** [comment]
so I've recently been testing running the EC in RO mode, and seems to work without issue on my TEEMO. I have a single USB-C cable connected to the monitor and nothing else. Firmware menus work, windows works, linux works. Only thing I can't do with the RO EC firmware is auto-power on when power is connected regardless of previous state -- that was a RW enhancement I added

**Comment by bam80** [comment]
Thanks for the update.
So you can reproduce the issue, but only in RW mode? Did you incorporate any changes to fix it?
Could we develop adoptable solution for other users suffering it?

**Comment by MrChromebox** [comment]
@bam80 the USB-PD issue is caused by the RO to RW transition, and so keeping the EC in RO mode mitigates that. The only change is a settings toggle in the UEFI Settings Menu to disable the EC-RW jump.

**Comment by bam80** [comment]
> The only change is a settings toggle in the UEFI Settings Menu to disable the EC-RW jump.

I didn't know about that menu (and probably didn't see it, did it appear in the recent FW versions?), could we document it somewhere, as it's not obvious at all it is tied to this issue?

**Comment by MrChromebox** [comment]
> I didn't know about that menu (and probably didn't see it, did it appear in the recent FW versions?), could we document it somewhere, as it's not obvious at all it is tied to this issue?

it doesn't exist in released firmware, I literally added it over the weekend just for testing. It appears to resolve the issue here, so I can offer it for testing shortly

**Comment by bam80** [comment]
> I can offer it for testing shortly

I'm eager to test it and confirm (or refute) your results, thank you!

**Comment by bam80** [comment]
Any update?

**Comment by MrChromebox** [comment]
haven't had a chance to get this ready for release unfortunately

**Comment by bam80** [comment]
> It appears to resolve the issue here, so I can offer it for testing shortly

How about the test build, just to make sure it fixes the problem for us, too?

**Comment by Parkeriscoo** [comment]
Also having this issue

**Comment by MrChromebox** [comment]
> Also having this issue

everyone is, it's broken in Google's EC code

**Comment by bam80** [comment]
Can report the issue is still there with 120W Xiaomi power adapter MDY-MI13PU.
At this point it would be really useful to have the test fw build where the problem is addressed.

I already invested to two of these Chromeboxes so current state is really unfortunate for me..

**Comment by bam80** [comment]
@MrChromebox generously sent me a test FW with an option to disable the EC-RW jump.
That helped me with the issue. Thank you, Matt!

If someone wants to be an early tester too, please ask him to send you the FW:
> I'll be adding/expanding the config options for all boards in the next release, so please don't post the test build just yet - others from GH can email me if they want to test it, but I don't want my test script URL getting posted since it's broken more often than not

And report your experience here.

Cheers.

**Comment by wylew** [comment]
Maybe similar issue?

Acer cx15, power over usb stops working after enabling CCD

**Comment by MrChromebox** [comment]
this issue is resolved in the 2503 firmware by disabling the use of the EC-RW firmware under the Platform Setup options

**Comment by bam80** [comment]
> this issue is resolved in the 2503 firmware by disabling the use of the EC-RW firmware under the Platform Setup options

@MrChromebox worth to be mentioned in the announce explicitly, I think:
https://docs.mrchromebox.tech/docs/news.html#mrchromebox-2503-0-release

**Comment by bam80** [comment]
@MrChromebox Many thanks, it works!

One note:
IMO, it worth to mention in the EC-RW menu entry description that it can be used as a workaround for USB-PD problems.
Otherwise, it's not clear why the menu entry exists and if it somehow tied to the PD at all.

**Comment by kasskas** [comment]
Hi. I tested today using latest FW (2503), but still ran into the issue described here. Disabling EC-RW firmware did not seem to solve the issue. Tried 2 chargers (100W ports), monitor with PD (90W) and power bank (100W and 45W ports), all of them showed the same behaviour: red LED blinking, nothing more happening. And described before, using original FW (with WP screw) has no issues. 
As this issue is marked as solved, should I open a new one, or we can re-open this one?

**Comment by bam80** [comment]
@kasskas maybe worth try to remove the screw. Unfortunately, I don't remember if I have mine in place..

**Comment by kasskas** [comment]
Tried removing, it blinks once without WP and still does not boot. If power button is pressed it does it again. With WP no need to press power button it does it by itself. @bam80 which FW are you using on yours? That pre-release with hotfix or official build? Maybe there is some small delta between them which causes issue to re-appear?

**Comment by bam80** [comment]
I use official build, just updated it with the script.
Did you try to fully remove power from the box? Sometimes it helps for weird issues.. (and if you don't remove it, EC is probably still keeps RW firmware variant).

**Comment by kasskas** [comment]
What do you mean by that? I power off (disconnect all power cables) for each test. I tried taking out coin cell too, no change.

**Comment by bam80** [comment]
Then the only thing left which comes to mind is your EC RO fw version is different than mine and the other people here.
If you feel adventurous, you could probably try to reflash it (having appropriate equipment, of course).

@MrChromebox would you help with identifying EC RO version?

**Comment by kasskas** [comment]
I tried with second one I got, same result (but I wouldn't be surprised they are from the same batch). I am always feeling adventurous, what equipment would I need? I think I am also hitting https://github.com/MrChromebox/firmware/issues/766 , but I dont think they are related?

**Comment by bam80** [comment]
There are many alternatives of flashing equipment, maybe the easiest one is self-made Suzy-Q cable.
But beware it won't help if you screw your EC RO up.

For in-board flashing and other things, you can get an impression here (I saw really cheap alternative programmers on Ali, too): 
https://docs.google.com/presentation/d/1eGPMu03vCxIO0a3oNX8Hmij_Qwwz6R6ViFC_1HlHOYQ/edit?pli=1&slide=id.gf4036fef_094#slide=id.gf4036fef_094
https://docs.google.com/presentation/d/1eGPMu03vCxIO0a3oNX8Hmij_Qwwz6R6ViFC_1HlHOYQ/edit?pli=1&slide=id.gf4036fef_0173#slide=id.gf4036fef_0173

<img width="512" height="384" alt="Image" src="https://github.com/user-attachments/assets/3605e5e4-ad94-4a0f-a5c0-b32717ca5091" />

**Comment by kasskas** [comment]
If I am getting a thing the I want to be able to unbrick it with the same one :D I got soldering station and access to better one if needed, so I guess proper flasher maybe is a better idea. is the ch341a is enough? I saw BIOS chip is SOIC so it should be pretty easy to attach, But as much as I understand from how-to EC has a different chip?

**Comment by bam80** [comment]
That is a muddy area for me too, so you got to clarify things for yourself (and share with us :).
Probably @MrChromebox has more knowledge, but last time I asked he didn't want to support EC RO reflash process :)

**Comment by kasskas** [comment]
<img width="800" height="600" alt="Image" src="https://github.com/user-attachments/assets/2c404223-1491-4907-bdfe-e98cfa2d5c8c" />
I was installing another system, and decided to try again with power from USB C. AND IT WORKED!. **Note: WP screw needs to be removed.** My guess that during my testing before it did not discharge the caps or something in that realm, as I tested with or without WP multiple times. As a test, I did same thing as I did before. Power on system with WP in place, red lights. Remove WP, try booting again, still red lights. No clue how long do you have to keep it "off" but several days seems to have worked. Once it is working, then there are no issues with turning it off/on again.

**Comment by bam80** [comment]
Congrats.
> No clue how long do you have to keep it "off" but several days seems to have worked.
 
@MrChromebox can we somehow programmatically force EC to pick up the RO fw, at least on the next boot?

**Comment by MrChromebox** [comment]
> [@MrChromebox](https://github.com/MrChromebox) can we somehow programmatically force EC to pick up the RO fw, at least on the next boot?

booting with the recovery button depressed might do it, otherwise I'd have to add some code to check if it's in RW and jump to RO if the RW jump option not selected

**Comment by bam80** [comment]
> booting with the recovery button depressed might do it

@kasskas could you try again and confirm?

**Comment by kasskas** [comment]
Tried:
* Pressing button, releasing then inserting USB C. Fails to boot
* Pressing button, inserting USB C releasing. Fails to boot
* Pressing button, inserting USB C, pressing power button, releasing. Fails to boot

**Comment by bam80** [comment]
@kasskas Thanks.
It's also interesting how long does it take for the capacitors to discharge.
The proper fix shouldn't rely on that, of course. Just curious.

**Comment by kasskas** [comment]
Overnight was not enough. Will check in 2 days then :D

**Comment by bam80** [comment]
@MrChromebox At this point, we should probably reopen the bug, until proper fix appears.

**Comment by MrChromebox** [comment]
I just  revisited the code, and it is set to reboot to RO if it boots in RW and the jump to RW option is not selected. So I'm not sure what exactly is going on here, since it works on both of my TEEMO boxes here

**Comment by kasskas** [comment]
Found the issue. It was between keyboard and the monitor 😅 Use RW EC was enabled. I was sure I turned it off, but I guess it was other chromebox... 
So at the end, issue was having WP in place. With RW EC disabled and WP removed I can finally boot from the USB C power source. Thanks @MrChromebox  and @bam80 for support.

**Comment by MrChromebox** [comment]
good news folks, pretty sure I've fixed the PD power issue when transitioning from RO->RW. doing a bit more testing now

**Comment by bam80** [comment]
> pretty sure I've fixed the PD power issue

Would love to hear any details!

**Comment by MrChromebox** [comment]
> Would love to hear any details!

https://github.com/MrChromebox/chrome-ec/commits/firmware-fizz-10139.B/

it's in the latest release, test with EC-RW enabled and see

**Comment by kasskas** [comment]
Checked on my system too, now it works with ECRW enabled. Tried flashing second system to double check but got 404 while downloading the script. I guess Cloudflare issues?

**Comment by MrChromebox** [comment]
> I guess Cloudflare issues?

no issue here, so hard to say

**Comment by bam80** [comment]
> https://github.com/MrChromebox/chrome-ec/commits/firmware-fizz-10139.B/

Wow, it seems huge work has been done here, are you going to upstream these patches?

**Comment by MrChromebox** [comment]
> > https://github.com/MrChromebox/chrome-ec/commits/firmware-fizz-10139.B/
> 
> Wow, it seems huge work has been done here, are you going to upstream these patches?

no, because Fizz is already in extended support, and they won't bother to release an ECRW update unless there's a bug raised by an OEM. And the issue is already fixed on newer devices (ie, puff Chromeboxes),

**Comment by pmnlla** [comment]
I think I've got the same exact issue with Snappy. is it possible to port these patches onto Snappy as well? 
Symptons are:
- Boots fine with battery
- Battery unplugged, bootloops - screen powers on, no coreboot logo
- Tried different chargers and wattages, no result.

**Comment by MrChromebox** [comment]
> I think I've got the same exact issue with Snappy. is it possible to port these patches onto Snappy as well?

completely different board, different EC, etc. Not all Chromebooks are designed to boot without a battery attached. The patches here would not apply to any other EC firmware

**Comment by pmnlla** [comment]
Should I file a new issue for this board then?

**Comment by MrChromebox** [comment]
> Should I file a new issue for this board then?

you can, I can't say that it will be a priority, EC firmware on a nearly decade old device, for which I don't have any schematics, for a function it wasn't originally intended to support.

**Comment by pmnlla** [comment]
ehh, im not expecting it to be a priority. this is moreso to keep things logged and leave a paper trail for people coming after me. 
a bulk of these machines are destined for the landfill anyways, hell i could send you one to test on just because i have so damn many of these
ill just wire 12v onto the battery connector and hopefully that will work

**Comment by movr4x** [comment]
@pmnlla 

Have you tried to disable EC jump to RW via "Use EC-RW Firmware" Platform Setup Menu option in EDK2?

This would make EC remain in RO.

If the issue is related, then this could be a strong hint.

**Comment by pmnlla** [comment]
I just tried toggling it, and guess what, the machine boots fine now! Without the EC jumping to the RW sector, the machine boots first try all the time even on low power adapters.

**Comment by CaptInsano** [comment]
I am still having this issue and am possible a bit confused about current recommended best settings in "Platform Setup Menu".
USB-C PD has never worked for me.

Current setup:
Asus Chromebox 3 (CN65) running latest firmware: 2512.1 at time of writing.
WP Screw removed
All "Platform setup menu" options reset to default and NVRAM was reset on update of firmware to lastest.

When I plug in a 100W USB-C power supply and try to boot I just get flashing red light for a moment and nothing else.

**Comment by MrChromebox** [comment]
@CaptInsano did you actually boot the device after the firmware update? That's necessary for the EC firmware to update

**Comment by CaptInsano** [comment]
@MrChromebox I booted the device via barrel-jack to see if the new firmware fixed the previous issues with "Restore AC power after loss" (it did!).

I then tried to power the device via USB-C PD (it had not worked for me on previously firmwares) and got the red flashing lights.

Current settings are:

EC Software Sync:  [Enabled]
Use EC-RW Firmware:  [Enabled]


I can provide video when I get home later.

**Comment by MrChromebox** [comment]
@CaptInsano if you're only getting a flashing red LED, then PD negotiation is failing for some reason. I'd try another adapter. You might also check that the CMOS battery is good

**Comment by movr4x** [comment]
@MrChromebox 

> [@CaptInsano](https://github.com/CaptInsano) if you're only getting a flashing red LED, then PD negotiation is failing for some reason. I'd try another adapter. You might also check that the CMOS battery is good

I think we can rule out CMOS battery problem, as it is required for bbram data retention after power loss, and the only way to inhibit auto power on (@CaptInsano confirmed this works) is via reset flags stored in bbram.

@CaptInsano 

Have you tried checking USB-C PD with `Use EC-RW Firmware` disabled? If this does not work even in EC RO, with jump to EC RW disabled during coreboot stage (when device is already booting), then likely your adapter is the issue here.

**Comment by CaptInsano** [comment]
Further testing & Info:

Asus Chromebox 3 (CN65) running latest firmware: 2512.1
i7 8550U version (incase it makes any difference)
Unlocked NVME speeds as per @MrChromebox post [here:](https://www.reddit.com/r/chromeos/comments/1kbzwxb/comment/mwhzf24) (Did this months ago and no issues since)


I checked CMOS battery with multimeter and reading approx 2.7V (seem acceptable), it also allows inhibition of auto power-on as per @movr4x above.

I re-flashed the most recent firmware (2512.1) and re-cleared NVRAM after I came home just to be sure.

Booted with barrel-jack to get into Platform setup menu.
My normal settings:
![Image](https://github.com/user-attachments/assets/d8cdaf29-d8d0-41f5-a03a-3b88179709aa)

**I have tested with `Use EC-RW Firmware` both enabled and disabled** (always saving settings and rebooting machine before powering off and testing USB-C PD)


**I have tested with an Anker 100W USB-C power supply and a Lenovo 65W USB-C power supply**


But I always get the following result shown below when I try to boot with USB-C connected:

https://github.com/user-attachments/assets/36197d15-14dc-4417-8fca-d4d20569fd46


Anything else I should be checking?

Thanks so much for your help and work on this project.

**Comment by kasskas** [comment]
I was able to reproduce similar (red light and does not bood, for me it cycles). *BUT* it does work if I set "Restore after AC loss" to "power on". @CaptInsano could you try like that?

**Comment by MrChromebox** [comment]
I just tested 3 different PD adapters here (including a USB-C monitor) on my i7-8550U TEEMO and it booted perfectly fine with all 3

**Comment by kasskas** [comment]
To double check, what was your setting for "Restore AC power after loss""?

**Comment by movr4x** [comment]
> To double check, what was your setting for "Restore AC power after loss""?

Does it work only if you set it to on? Or does previous state also work?

**Comment by kasskas** [comment]
Just checked. If I shut it down nicely via OS, with "previous state" option it fails to boot again.

**Comment by CaptInsano** [comment]
Progress!

If I change `Restore after AC loss` to "power on" I CAN boot with USB-C PD (checked with both previous power adaptors and now even boots via my monitor USB-C PD connection (60W) (providing power, video and USB hub function with one cable)).

Testing:
If I keep the USB-C connected after booting as above I can also change `Restore after AC loss` to back to "power off (s5)" and the machine still boots (as far as bios anyway) **but if I then remove the USB-C PD cable** and reconnect it goes back to the flashing red LED as per my video above.

**Comment by kasskas** [comment]
That matches with what I have seen too. I guess issue is with the cold boot then. That also would explain why reproduction is annoying (if you change setting, shut it down and try to boot again it will work)

**Comment by movr4x** [comment]
Thanks guys for the input, I will look into this.

**Comment by CaptInsano** [comment]
~~Kind of surprisingly though:~~

~~If I have `Restore after AC loss` to "power on" and connect my USB-C PD cable: the device does not auto-power on as expected. based on that setting.~~

~~It will boot when I press the button but not "Restore after AC loss".~~

EDIT: Ignore the above, it does seem to auto-boot most times



As per other users:
I again tested with "previous state" and "power off (s5)" and neither allow a cold boot from USB-C PD.

**Comment by kasskas** [comment]
Hmm, that is a difference from my machine. When I plug it in, it blinks red led twice and then power on. I use 100W USB-PD. Have you tried with other adapter?

**Comment by CaptInsano** [comment]
I had been testing with the 100W adaptor but I must have been having an issue because now it is respecting `Restore after AC power loss`  as expected most times I unplug and re-plug the device with USB-C.

I have edited my previous post so not to add extra confusion

**Comment by movr4x** [comment]
@kasskas @CaptInsano 

Could one of you test my new patch? At the moment I am unable to test USB-C PD.

This is based on `2512.1`.

You can use official `firmware-util.sh` (option `4`) to flash custom firmware.

Attached archive contains two files, one is actual rom, the other is SHA1 checksum, be sure to verify rom with `sha1sum` before flashing it.

How to test this:
- Make sure both `EC Software Sync` and `Use EC-RW Firmware` are enabled.
- Make sure `Restore after AC loss` is set to `Power Off (S5)`.
- Flash firmware (make sure to use `.rom` file and not `.rom.sha1`).
- Reboot the device, and wait until it boots.
- Unplug barrel jack (either from a running system or after powering it down), wait at least 30 seconds, plug USB-C PD and check if the device can boot now with USB-C PD and `Power Off (S5)`..

[coreboot-2512-fizz-30ec70fa.tar.gz](https://github.com/user-attachments/files/24839741/coreboot-2512-fizz-30ec70fa.tar.gz)

**Comment by CaptInsano** [comment]
Same situation unfortunately:

Flashed the new custom firmware. (Making sure that both `EC Software Sync` and `Use EC-RW Firmware` are enabled and also that `Restore after AC loss` is set to `Power Off (S5)`

When I disconnected the barrel jack, waited 30+ secs and connected my 100W USB-C adapter I got the same briefly flashing red LED and no boot on pressing the power button. (Exactly like my video above)

When I connected barrel jack again and changed `Restore after AC loss` to `Power On` it would boot.
If I then left the USB-C connected and changed `Restore after AC loss` back to  `Power Off (S5)` and rebooted via BIOS it would reboot or power back on from a shutdown. 
HOWEVER (like before) if I removed the USB-C while `Restore after AC loss` was still set to `Power Off (S5)` I could not power up again (cold boot).

**Comment by movr4x** [comment]
@CaptInsano 

> Same situation unfortunately:

You have mentioned earlier that you were also unable to boot when `Use EC-RW Firmware` was set to `Disabled`. We need to investigate this further before we touch EC RW.

First: 
- Unplug USB-C and plug barrel jack.
- Press power button to power the device on and open setup menu.
- Set `Restore after AC loss` to `Power on (S0)`. Save.
- Reboot to apply new changes, and immediately after reboot (no need to boot to OS) open setup menu again.
- Set `Use EC-RW Firmware` and `EC Software Sync` to `Disabled`. Save.
- Reboot to apply new changes, and immediately after reboot open setup menu again.
- Press power button to gracefully power the device off, wait at least 15 seconds.
- Press power button to power it on.
- Once booted, use cbmem from `https://mrchromebox.tech/files/util/cbmem.tar.gz`, unpack it, and dump cbmem with `sudo ./cbmem -1 >./cbmem.txt`.
- Use `grep -F 'running image' ./cbmem.txt`, you should only get `running image: 1`. This will confirm that the only used image is EC RO with no EC RW interference.
- You can also check if line `Set power on after power failure` is present in `cbmem.txt`. This will confirm that Intel register is configured to `Power on (S0)`.
- Gracefully power off your machine, wait at least 15 seconds. Keep barrel jack plugged.

First two tests will be done with `Power on (S0)` set earlier.

Test 1 (no bbram OFF flag): 
- Press power button to power the device on and open setup menu (do not change anything).
- Pull the plug to force unclean shutdown. This will make EC RO skip saving OFF bbram flag. Wait at least 30 seconds.
- Plug USB-C PD, **observe and note** what will happen (did it successfully auto power on and boot?).
- Power down the machine (if on).
- Unplug USB-C PD, wait at least 30 seconds, and plug barrel jack, if the device will auto power on then gracefully shut it down.

Test 2 (bbram OFF flag): 
- Press power button to power the device on and open setup menu (do not change anything).
- Press power button to gracefully shut it down. This will make EC RO save OFF bbram flag. Wait at least 15 seconds.
- Unplug barrel jack and wait at least 30 seconds.
- Plug USB-C PD, **observe and note** what will happen (did it remain off?).
- Press power button (if off), **observe and note** what will happen (did it boot?).
- Power down the machine (if on).
- Unplug USB-C PD, wait at least 30 seconds, and plug barrel jack, if the device will auto power on then gracefully shut it down.

Now switch to `Power off (S5)`: 
- Press power button to power the device on and open setup menu.
- Set `Restore after AC loss` to `Power off (S5)`. Save.
- Reboot to apply new changes, and immediately after reboot open setup again.
- Gracefully power off your machine, wait at least 15 seconds. Keep barrel jack plugged.

Repeat both tests, this time with `Power off (S5)`, and observe/note what will happen.

If you will find some time to do this, then it would be very helpful, as this should allow to better understand what prevents EC RO from successfully booting when EC RW is taken out of equation.

**Comment by CaptInsano** [comment]
Confirmed:
`running image: 1` & `Set power on after power failure` is present in cbmem.txt.

below is my cbmem.txt incase it is useful:

[cbmem.txt](https://github.com/user-attachments/files/24857686/cbmem.txt)

<br>
<ins>**RUNNING TESTS:**</ins>
<br>
<br>

<ins>Power on (S0)</ins>: Test 1 (no bbram OFF flag):

Press power button to power the device on and open setup menu (do not change anything).
Pull the plug to force unclean shutdown. This will make EC RO skip saving OFF bbram flag. Wait at least 30 seconds.

Plug USB-C PD, observe and note what will happen (did it successfully auto power on and boot?).
<ins>**>> Powered on automatically with USB-C**</ins>

Power down the machine (if on). <ins>**(I made an assumption and did a clean power down here)**</ins>
Unplug USB-C PD, wait at least 30 seconds, and plug barrel jack, if the device will auto power on then gracefully shut it down.
<ins>**>>Device did NOT turn on automatically**</ins>

Power down the machine (if on). (unclean)
Unplug USB-C PD, wait at least 30 seconds, and plug barrel jack, if the device will auto power on then gracefully shut it down.
<ins>**>>Device did turn on automatically**</ins>



<ins>Power on (S0)</ins>: Test 2 (bbram OFF flag):

Press power button to power the device on and open setup menu (do not change anything).
Press power button to gracefully shut it down. This will make EC RO save OFF bbram flag. Wait at least 15 seconds.
Unplug barrel jack and wait at least 30 seconds.
Plug USB-C PD, observe and note what will happen (did it remain off?).
<ins>**>> Remained off**</ins>

Press power button (if off), observe and note what will happen (did it boot?).
<ins>**>>Yes it booted**</ins>

Power down the machine (if on).
Unplug USB-C PD, wait at least 30 seconds, and plug barrel jack, if the device will auto power on then gracefully shut it down.
<ins>**>> Did NOT turn on automatically on barrel-jack insertion.**</ins>


Now switch to Power off (S5):

Press power button to power the device on and open setup menu.
Set Restore after AC loss to Power off (S5). Save.
Reboot to apply new changes, and immediately after reboot open setup again.
Gracefully power off your machine, wait at least 15 seconds. Keep barrel jack plugged.

Repeat both tests, this time with Power off (S5), and observe/note what will happen.

<ins>Power off (S5)</ins>: Test 1 (no bbram OFF flag):

Press power button to power the device on and open setup menu (do not change anything).
Pull the plug to force unclean shutdown. This will make EC RO skip saving OFF bbram flag. Wait at least 30 seconds.

Plug USB-C PD, observe and note what will happen (did it successfully auto power on and boot?).
<ins>**>> No auto boot & no boot on power button press**</ins>


Power down the machine (if on). (device not on as directly above)
Unplug USB-C PD, wait at least 30 seconds, and plug barrel jack, if the device will auto power on then gracefully shut it down.
<ins>**>>Device did turn on automatically**</ins>



<ins>Power off (S5)</ins>: Test 2 (bbram OFF flag):

Press power button to power the device on and open setup menu (do not change anything).
Press power button to gracefully shut it down. This will make EC RO save OFF bbram flag. Wait at least 15 seconds.
Unplug barrel jack and wait at least 30 seconds.
Plug USB-C PD, observe and note what will happen (did it remain off?).
<ins>**>> Remained off**</ins>

Press power button (if off), observe and note what will happen (did it boot?).
<ins>**>>No boot, flashing red light**</ins>

Power down the machine (if on).
Unplug USB-C PD, wait at least 30 seconds, and plug barrel jack, if the device will auto power on then gracefully shut it down.
<ins>**>> DID turn on automatically on barrel-jack insertion.**</ins>

**Comment by movr4x** [comment]
@CaptInsano 

Nice work, I really appreciate your feedback.

Option `Restore after AC loss` is used in coreboot to configure: 
- EC own After G3 setting (only since 2512.0, and only if running EC RW) to match user preference for After G3 from setup menu.
- Intel chipset register related to After G3.

This Intel register for Skylake/KabyLake 100 series chipset is defined in `Intel 100 Series Chipset Family Platform Controller Hub (PCH): Datasheet - Volume 2 - Page 152` from Intel website as follows: 
```
GEN_PMCON_B - Offset A4h
CFG Register (Size: 32 bits)
Device 31 - Function 2

Bit 0: AG3E - AFTERG3_EN
Default value: 0h
Access: RW

Description:
Determines what state to go to when power is reapplied after a power failure (G3 state).
0 = System will return to an S0 state (boot) after power is re-applied.
1 = System will return to the S5 state (except if it was in S4, in which case
    it will return to S4-like-state). In the S5 state, the only enabled wake-up
    event is the Power Button or any enabled wake event that was preserved
    through the power failure.
This bit is in the RTC well and is only cleared by RTCRST# assertion.
```

Based on your input, using USB-C PD from unpowered state and jump to EC RW disabled:
- `Power on (S0)` with unclean shutdown (no EC bbram flag, Intel register set to 0) - allows to boot, and does it automatically - **this is ok**.
- `Power on (S0)` with clean shutdown (EC bbram flag set, Intel register set to 0) - also allows to boot, and only does it after power button press - **this is ok**.
- `Power off (S5)` with unclean shutdown (no EC bbram flag, Intel register set to 1) - does not allow to boot. - **this is not ok**.
- `Power off (S5)` with clean shutdown (EC bbram flag set, Intel register set to 1) - does not allow to boot. - **this is not ok**.

If you performed the tests correctly (which looks like you did), then we can rule out EC bbram flag as the culprit, since your device has booted fine using USB-C PD regardless if it was set or not.

This means our main suspect now is Intel chipset register, as boot was possible only if it was set to 0.

EC is usually able to bypass this register, for example by simulating power button press to PCH to power the device on (even if set to 1), or by controlling specific GPIOs and/or power rails to prevent auto boot (even if set to 0).

But it seems that using USB-C PD changes somehow the dynamic here, giving this register more control over what is going on when booting, as compared to using barrel jack. Perhaps power button pulse from EC does not reach PCH in time (or is not emitted), so PCH assumes the device should remain in S5, as no wake event is seen, dunno.

To test this I will alter how this register is updated in coreboot, and check (to be sure) if this change does not break anything when using barrel jack, then I will share this rom with you to confirm if USB-C PD is also fine and working (in both EC RO and EC RW).

**Comment by movr4x** [comment]
@CaptInsano 

I have tested new change. Forcing Intel chipset AG3E option to be always 0 results in no regression when using barrel jack: 
- No difference in power draw when the device is initially off after restoring power.
- All After G3 options in setup menu work as expected when EC RW is used.

Not really a surprise, I have expected this outcome.

Now we need to check if this fixes booting issue when using USB-C PD.

I have reverted ChromeEC for FIZZ to the one officially used in 2512.1. This new image only changes coreboot to make sure Intel chipset AG3E option is always updated to 0.

As previously, attached archive contains two files, one is actual rom, the other is SHA1 checksum.

How to proceed: 
- Use only barrel jack.
- Set both `EC Software Sync` and `Use EC-RW Firmware` to `Enabled`.
- Set `Restore AC power after loss` to `Power Off (S5)`.
- Save new changes and reboot.
- Verify unpacked `.rom` with `sha1sum` before flashing.
- Flash firmware (make sure to use `.rom` file and not `.rom.sha1`).
- Reboot the device, and wait until it boots.
- Reboot one more time, and wait until it boots.
- Use `https://mrchromebox.tech/files/util/cbmem.tar.gz` to dump cbmem with `sudo ./cbmem -1 >./cbmem.txt`. Your dump should contain: 
```
[INFO ]  Set power on after power failure.
[...]
[DEBUG]  Google Chrome EC: version:
[...]
[DEBUG]         rw: fizz_v1.1.7930-cc6bc622b0
[DEBUG]    running image: 2
[...]
[INFO ]  ChromeEC After G3 State: Syncing to 'off'
# There should be no error after above line.
```
- Reboot your device and open setup menu.
- Unplug barrel jack, while in setup menu, to force unclean shutdown. Wait 30 seconds.

Now actual test: 
- Plug power via USB-C. Device should remain off.
- Press power button. Device should boot.

[coreboot-2512-fizz-d51e064b.tar.gz](https://github.com/user-attachments/files/24886031/coreboot-2512-fizz-d51e064b.tar.gz)

**Comment by CaptInsano** [comment]
@movr4x 


> Now actual test:
> 
> * Plug power via USB-C. Device should remain off.
> * Press power button. Device should boot.


### Success!! 

Exactly as expected: device remains off when power connected by either barrel jack or USB-PD after unclean shutdown but **SUCCESSFULLY** boots when power button pressed!

<br>
<br>
Thank you so much for your work on this!

**Comment by movr4x** [comment]
@CaptInsano 

> Thank you so much for your work on this!

It would not be possible to solve this so quickly without your help. I would need to order a USB-C power supply, and even then I would not have 100% guarantee I would be able to replicate this issue to locate the problem as easily.

And the problem turned out not to be related to EC RW at all, as the main CPU is never woken up to execute coreboot (which forces the jump from EC RO to EC RW after power loss, in the context of MrChromebox firmware).

Still, I am curious how official EC RO, which is normally able to force chipset to do what it wants (either keep the device off or auto power it on), regardless of Intel chipset AG3E configuration, is failing in that one specific scenario when attempting to boot using USB-C PD after power loss and chipset AG3E set to 1.

Coreboot has been writing to this Intel register for a long time. This means that even in older firmware versions (pre-2512), users would also experience issues attempting to boot the device using USB-C PD after power loss if chipset AG3E would be set to 1. This would be the case if `Restore AC after power loss` is set to `Power off (S5)` or after clean shutdown if set to `Previous state`.

Interestingly, @MrChromebox also made a change back in 2509.4, which removed `Restore AC after power loss` option for Chromebooks, stating in the commit message that beside not working (this is expected) it was also causing problems: 
https://github.com/MrChromebox/coreboot/commit/5cd36fa4

Anyway, I will have to discuss with @MrChromebox how to properly fix this. Hopefully, we will be able to reach an agreement and land a fix in the next [point] release.

**Comment by bam80** [comment]
Any progress on this? Please keep us informed.
Hopefully the fix will happen before the next release.
Thanks!
