### ISSUE TITLE
LUMPY firmware upgrade stops headphone socket from disconnecting internal speakers.

### ISSUE THREAD

**Issue by an-Awake-Idea** [MrChromebox/firmware#837]
Hi, I've just installed the LUMPY firmware on a Samsung Chromebook Series 5 550, and now, after having tested it with MX-Linux, the internal speakers don't switch off after headphones are plugged in.

Would I be correct in thinking that it's the firmware which is responsible? And if so, is there anything that can be done to rectify it?

**Comment by MrChromebox** [comment]
could be a Linux issue or a firmware one, but I'd think if it were a firmware one I'd have had someone reported it before now. The audio codec programming for LUMPY hasn't been touched in 5 years. but I'll check the presence-detect flag on the headphones

**Comment by MrChromebox** [comment]
I took a quick look at the HDA verbs and it seems that the speakers and mic both had presence detect set - I've corrected that, so flash this update manually and see if that resolves the issue

[coreboot_edk2-lumpy-mrchromebox_20251125.zip](https://github.com/user-attachments/files/23752610/coreboot_edk2-lumpy-mrchromebox_20251125.zip)

**Comment by an-Awake-Idea** [comment]
Thank you so much, I never imagined there'd be such a quick fix. However, I've only just found the time to deal with it.

Anyway, with me being a bit of a Linux newbie, and this my first ever Linux install on a firmware updated Chromebook, I've just attempted the Manual Flashing Procedure, and after successfully completing Step 1, I've run into the following problem with Step 2. Any ideas?

`$ sudo ./flashrom -p internal -r backup.rom --ifd -i bios
[sudo] password for D:     
flashrom MrChromebox-1.4.0-devel_2024.04.18 (git:v1.2-1418-ge5ed0c6340) on Linux 6.12.57+deb13-amd64 (x86_64)
flashrom is free software, get the source code at https://flashrom.org/

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
coreboot table found at 0xace54000.
Found chipset "Intel HM65".
Enabling flash write... Error accessing ICH RCRB, 0x4000 bytes at 0x00000000fed1c000
/dev/mem mmap failed: Operation not permitted
FAILED!
FATAL ERROR!
Error: Programmer initialization failed.`

**Comment by MrChromebox** [comment]
no manual flashing is necessary or recommended. and the fix is now in the latest release, so you can simply update to the 2509.4 release using the script and it should be resolved.

**Comment by an-Awake-Idea** [comment]
Thank you again. However, when I try and run the Firmware Utility Script by executing the `cd; curl -LOf https://mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh` command in MX-Linux's Xfce Terminal Emulator, I get the following. Can you advise?

`MrChromebox Firmware Utility Script starting up

Downloading supporting files...

Downloading required tools...

Getting device/system info...

Flashrom is unable to read current firmware; cannot continue:

flashrom MrChromebox-v1.5.0 (git:v1.5.0-5-g255f289445) on Linux 6.12.57+deb13-amd64 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

coreboot table found at 0xace54000.
Found chipset "Intel HM65".
Enabling flash write... Error accessing ICH RCRB, 0x4000 bytes at 0x00000000fed1c000
/dev/mem mmap failed: Operation not permitted
FAILED!
FATAL ERROR!
Error: Programmer initialization failed.

You may need to add 'iomem=relaxed' to your kernel parameters,
or trying running from a Live USB with a more permissive kernel (eg, Ubuntu 23.04+).

If you have UEFI SecureBoot enabled, you need to disable it to run 
the script/update your firmware.

MrChromebox Firmware Utility setup was unsuccessful
 * diagnosics report has been saved to /tmp/mrchromebox_diag.txt
 * go to https://forum.chrultrabook.com/ for help`

**Comment by MrChromebox** [comment]
you need to disable secure boot as per the msg, or boot a live USB with a more permissive kernel, like Ubuntu

**Comment by an-Awake-Idea** [comment]
Ok, I created a bootable Ubuntu USB which successfully ran the Firmware Utility Script, and I got the following confirmation from my 'Quick System Info':

`Mobo: SAMSUNG model: Lumpy v: 1.0 serial: <superuser required> UEFI: coreboot v: MrChromebox-2509.4 date: 11/30/2025`

However, the internal speakers are still not disconnecting when headphones are plugged in. Any ideas?

**Comment by MrChromebox** [comment]
wonder if Linux is applying some overrides that is breaking it, because the coreboot side is correct now

**Comment by an-Awake-Idea** [comment]
I've just tried it again but this time with USB boots of both MX-Linux and Ubuntu instead of the installed version of MX-Linux, and it's just the same.

Before I updated the firmware, it definitely used to work because I used to have it connected to my audio system and I'd have noticed if it had still been playing through its internal speakers at the same time.

**Comment by MrChromebox** [comment]
> Before I updated the firmware

meaning when you were running ChromeOS?

You changed the firmware and the OS/kernel etc. Quite possible Google fixed the issue in ChromeOS and it was never upstreamed. You can dump the HDA verbs from Linux and we can see if they are being changed from what the firmware sets.

**Comment by an-Awake-Idea** [comment]
Yes, when I was running ChromeOS.

And how would I go about dumping the HDA verbs from Linux?

**Comment by MrChromebox** [comment]
try this build: download, extract, then flash using the custom ROM option of the script. not manual flash.

[coreboot_edk2-lumpy-mrchromebox_20251203.zip](https://github.com/user-attachments/files/23917659/coreboot_edk2-lumpy-mrchromebox_20251203.zip)

**Comment by an-Awake-Idea** [comment]
Thanks, I've flashed it and the QSI now shows: `UEFI: coreboot v: MrChromebox-2509.4-dirty date: 11/30/2025`

However, after rebooting, it's still not switching off the internal speakers when headphones are connected, but looking at the 'Volume Control' window from the 'PulseAudio Panel Plugin', it does at least register when the headphones are plugged in and unplugged - sound just plays through both together.

**Comment by MrChromebox** [comment]
[coreboot_edk2-lumpy-mrchromebox_20251203.zip](https://github.com/user-attachments/files/23918540/coreboot_edk2-lumpy-mrchromebox_20251203.zip)

made a few tweaks, this is different from the original ChromeOS config but I don't have a good way to debug this

**Comment by an-Awake-Idea** [comment]
It's still the same, but I appreciate you having a go and just how challenging it must be, so if there's anything I can provide which would help (and if you can explain how to provide it) please let me know.

**Comment by MrChromebox** [comment]
dumping the HDA verbs from Linux to compare to what coreboot is programming would be a good place to start. I don't have a good link for doing that handy.
